#!/bin/bash

export TOPLEVEL=$HOME

export ACME_HOME=$TOPLEVEL/ACME
export KERNEL_BUILD=$ACME_HOME/kbuild
export ACME_PATCHES=$ACME_HOME/patches
export KERNEL_SRC=$ACME_HOME/linux
export TFTP_DIR=/var/lib/tftpboot

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-

#
# Note on using NFS: this will work nicely if the
# buildroot output/image dir is exported and used as scratch
# nfs rootfs.
#
export INSTALL_MOD_PATH=$ACME_HOME/buildroot/output/images

if [  -f cp ~/.vimrc_ACME ~/.vimrc  ]
then
	echo "setting git ID and vim prefs."
	cp ~/.gitconfig_BAYLIBRE ~/.gitconfig
	cp ~/.vimrc_ACME ~/.vimrc
fi

