#!/bin/bash

export SERVERIP=`hostname -I`
export BOARDIP=192.168.1.69

# Uncomment when using a build server # 
export USE_BUILD_SERVER=build.baylibre.com

export TOPLEVEL=`pwd`

export ACME_HOME=$TOPLEVEL

export ACME_PATCHES=$ACME_HOME/patches
export KERNEL_SRC=$ACME_HOME/linux
export UBOOT_SRC=$ACME_HOME/u-boot

export TFTP_DIR=/var/lib/tftpboot

export ARCH=arm
#export CROSS_COMPILE=arm-linux-gnueabi-
export CROSS_COMPILE=arm-linux-gnueabihf-

# Uncomment to experiment with IIO
#
export ACME_IIO=1

#
# Note on using NFS: this will work nicely if the
# buildroot output/image dir is exported and used as scratch
# nfs rootfs.
#
export INSTALL_MOD_PATH=$ACME_HOME/rootfs

if [ -f ~/.vimrc_ACME ]
then
	echo "setting git ID and vim prefs."
	cp ~/.gitconfig_BAYLIBRE ~/.gitconfig
	cp ~/.vimrc_ACME ~/.vimrc
fi

