#!/bin/bash

export SERVERIP=`hostname -I`
export BOARDIP=192.168.1.69

# Uncomment when using a build server #
#export USE_BUILD_SERVER=build.baylibre.com
#export CROSS_COMPILE=arm-linux-gnueabihf-

export CROSS_COMPILE=arm-linux-gnueabi-

export COMMON=~/COMMON
export TOPLEVEL=`pwd`
export PATH=$PATH:$TOPLEVEL/bin

export ACME_PATCHES=$TOPLEVEL/patches

# Try using a common local git clone for linux
# As for CI will will usually checkout the tag-to-test
#
if [ -d "$COMMON/linux" ]
then
	echo "WARNING: will use the COMMON source for linux"
        export KERNEL_SRC=$COMMON/linux
else
	export KERNEL_SRC=$TOPLEVEL/linux
fi


if [ -d "$COMMON/u-boot" ]
then
	echo "WARNING: will use the COMMON source for u-boot"
        export UBOOT_SRC=$COMMON/u-boot
else
        export UBOOT_SRC=$TOPLEVEL/u-boot
fi


export TFTP_DIR=$TOPLEVEL/build/tftpboot

export ARCH=arm

#
# Note on using NFS: this will work nicely if the
# buildroot output/image dir is exported and used as scratch
# nfs rootfs.
#
export INSTALL_MOD_PATH=$TOPLEVEL/rootfs

# Uncomment to experiment with IIO
#
export ACME_IIO=1

if [ -f ~/.vimrc_ACME ]
then
	echo "setting git ID and vim prefs."
	cp ~/.gitconfig_BAYLIBRE ~/.gitconfig
	cp ~/.vimrc_ACME ~/.vimrc
fi

